name: Node.js CI

on:
  push:
    branches:
      - master
      - next
    paths-ignore:
      - 'bench/**'
      - 'examples/**'
  pull_request:
    branches:
      - master
      - next
    paths-ignore:
      - 'bench/**'
      - 'examples/**'

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [8, 10, 12]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}

    - name: (env) pnpm
      run: curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node

    - name: Install
      run: |
        pnpm install
        pnpm add -g nyc

    - name: Linter
      run: pnpm linter

    - name: Test w/ Coverage
      run: nyc --include=packages pnpm test

    - name: Report
      if: matrix.nodejs >= 12
      run: |
        nyc report --reporter=text-lcov > coverage.lcov
        bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
